### ISSUE TITLE
Run on PC without Webcam

### ISSUE THREAD

**Issue by thepian** [sipeed/MaixPy3#15]
If I run maixpy3 scripts on a LinuxVM (docker) without a webcam available, it fails badly. It should be possible to at least
import the modules. Nice to have would be that only features that need the hardware are switched off.

This will enable developing Python scripts that depend on maix, and run CI builds.

```
[display] tips: os.environ(export) not _MAIX_WIDTH_ or _MAIX_HEIGHT_.
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
assets path= /MaixPy3/home/occi/assets - reactions path= /MaixPy3/home/occi/reactions
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    import occi_default
  File "/MaixPy3/home/occi_default/__init__.py", line 3, in <module>
    from maix import nn
  File "/opt/conda/lib/python3.7/site-packages/maix/nn.py", line 1, in <module>
    from _maix_nn import *
ModuleNotFoundError: No module named '_maix_nn'
```

**Comment by junhuanchen** [comment]
update this https://pypi.org/project/MaixPy3/0.3.2/
